// Source-authentic PT world connection graph, generated by
// `node scripts/pt-port/pt_map.mjs maplinks` (also emitted by compile-all)
// into generated/pt-maps/maplinks.json. Every record is parsed out of the
// MagicPT-Chinese source (see `generatedFrom` for the file list); nothing
// here is invented, and nothing here MUTATES the world - this module is a
// read-only index the /ptmaplinks dev command and the E2E harnesses query.
//
// Coordinates are PT engine units (the same frame the manifest gates and
// WarpGate triggers use; PtMapDescriptor.transform converts to world space).

export interface PtLinkField {
  fieldIndex: number;
  id: string | null;
  mapName: string | null;
  displayName: string | null;
  asePath: string;
  state: string | null;
  limitLevel: number;
  centerPos: [number, number] | null;
  startPoints: [number, number][];
  posWarpOut: { x: number; y: number; z: number } | null;
  component: number;
  reachability: 'foot' | 'warp' | 'ui-item' | 'server' | 'isolated';
  /** Phase 6G sea-edge spec (scripts/pt-port/lib/sea_edges.mjs): null when
   *  no void-facing bounds edge carries water. Shape mirrors PtSeaSpec. */
  sea?: {
    edges: {
      edge: 'minX' | 'maxX' | 'minZ' | 'maxZ';
      from: number;
      to: number;
      reach: number;
      level: number;
      materialIndex: number;
      uScale: number;
      vScale: number;
    }[];
  } | null;
}

export interface PtFieldGateEdge {
  from: number;
  to: number;
  fromId: string | null;
  toId: string | null;
  x: number;
  z: number;
  y: number;
  bidirectional: true;
  authoredIn: number;
  dead?: boolean;
}

export interface PtWarpGateRec {
  field: number;
  fieldId: string | null;
  x: number;
  z: number;
  y: number;
  size: number;
  height: number;
  limitLevel: number;
  specialEffect: number;
  exits: { to: number; toId: string | null; x: number; z: number; y: number }[];
}

export interface PtWingWarp {
  destinations: {
    icon: number;
    fieldIndex: number;
    fieldId: string | null;
    name: string | null;
    doc: string | null;
    iconPos: [number, number] | null;
    requiredLevel: number;
  }[];
  haGate: {
    fieldIndex: number | null;
    fieldId: string | null;
    name: string | null;
    doc: string | null;
    iconPos: [number, number] | null;
    requiresBlessCastleClan: boolean;
  };
  costs: number[];
  tiers: { item: string; unlockCount: number }[];
  defaultUnlock: number;
  rules: {
    freeIconsBelow: number;
    paidWhenUnlockAtLeast: number;
    costIndexBase: number;
    sameAreaFree: boolean;
    levelGate: string;
    arrival: string;
    trigger: string;
  };
}

export interface PtNpcTeleport {
  destinations: {
    select: number;
    fieldIndex: number;
    fieldId: string | null;
    cost: number | null;
    levelGateField: number | null;
  }[];
  arrival: string;
  costIncludesSiegeTax: boolean;
  dungeonTeleport: { fieldIndex: number };
  castleTeleport: { fieldIndex: number };
  warTeleport: { fieldIndex: number; server: boolean };
  fallGame: { fieldIndex: number };
  jobChangeReturn: { tempskron: number; morion: number };
}

export interface PtServerTransition {
  kind: string;
  fieldIndex: number | null;
  fieldId: string | null;
  x?: number;
  z?: number;
  source: string;
}

export interface PtMapLinks {
  generatedFrom: string[];
  fieldCount: number;
  startFields: Record<string, number>;
  fields: PtLinkField[];
  fieldGates: PtFieldGateEdge[];
  warpGates: PtWarpGateRec[];
  wingWarp: PtWingWarp;
  npcTeleport: PtNpcTeleport;
  teleportCore: { select: number; fieldIndex: number; fieldId: string | null; level: number }[];
  etherCore: { item: string; fieldIndex: number; fieldId: string | null; startFieldDefine: string }[];
  serverTransitions: PtServerTransition[];
}

const LINKS = import.meta.glob('../../generated/pt-maps/maplinks.json', {
  eager: true,
  import: 'default',
}) as Record<string, PtMapLinks>;

function graph(): PtMapLinks | null {
  const g = LINKS['../../generated/pt-maps/maplinks.json'];
  return g ?? null;
}

/** The full source-derived graph, or null when the artifact is absent. */
export function ptMapLinksGraph(): PtMapLinks | null {
  return graph();
}

export interface PtFieldLinks {
  field: PtLinkField;
  /** Undirected FieldGate edges touching this field (either direction). */
  fieldGates: { other: number; otherId: string | null; x: number; z: number; y: number; authoredIn: number; dead: boolean }[];
  /** WarpGate triggers physically inside this field. */
  warpGates: PtWarpGateRec[];
  /** WarpGate exits (from any field) that land in this field. */
  warpInbound: { fromField: number; fromFieldId: string | null; exit: PtWarpGateRec['exits'][number]; specialEffect: number }[];
  /** Non-null when this field hosts a SpecialEffect=2 wing gate. */
  wingDestinations: PtWingWarp['destinations'] | null;
  /** Server/event transitions that land in this field. */
  serverInbound: PtServerTransition[];
}

/** All source-defined links for one field (by field index or package id). */
export function ptMapLinksForField(ref: number | string): PtFieldLinks | null {
  const g = graph();
  if (!g) return null;
  const field =
    typeof ref === 'number'
      ? g.fields.find((f) => f.fieldIndex === ref)
      : g.fields.find((f) => f.id === ref || f.mapName === ref);
  if (!field) return null;
  const fi = field.fieldIndex;

  const fieldGates = g.fieldGates
    .filter((e) => e.from === fi || e.to === fi)
    .map((e) => ({
      other: e.from === fi ? e.to : e.from,
      otherId: e.from === fi ? e.toId : e.fromId,
      x: e.x,
      z: e.z,
      y: e.y,
      authoredIn: e.authoredIn,
      dead: e.dead ?? false,
    }));

  const warpGates = g.warpGates.filter((w) => w.field === fi);

  const warpInbound: PtFieldLinks['warpInbound'] = [];
  for (const w of g.warpGates) {
    for (const exit of w.exits) {
      if (exit.to === fi) {
        warpInbound.push({ fromField: w.field, fromFieldId: w.fieldId, exit, specialEffect: w.specialEffect });
      }
    }
  }

  const wingDestinations = warpGates.some((w) => w.specialEffect === 2)
    ? g.wingWarp.destinations
    : null;

  const serverInbound = g.serverTransitions.filter((t) => t.fieldIndex === fi);

  return { field, fieldGates, warpGates, warpInbound, wingDestinations, serverInbound };
}
