// Build the canonical PT skill catalog.
//
//   node scripts/pt-port/build_pt_skills.mjs
//
// Sources (resolved via scripts/pt-port/lib/pt_client.mjs env overrides):
//   PT-Source/sinbaram/sinSkill.h       skill codes: GROUP_*|CHANGE_JOB*|SKILL_*
//   PT-Source/sinbaram/sinSkill.cpp     sSkill[] roster order + icon filenames
//   PT-Source/sinbaram/sinSkill_Info.h  per-skill requirements + ini mana key
//   Server/skill.ini                    per-rank (1..10) numeric tables
//
// Emits generated/pt-maps/pt_skill_catalog.generated.ts (never hand-edit).

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ptServerPath, ptSourcePath } from './lib/pt_client.mjs';
import { buildSkillCatalog } from './lib/pt_skills.mjs';

const GBK = new TextDecoder('gbk');
const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

const HEADER = `// GENERATED by scripts/pt-port/build_pt_skills.mjs, do not edit by hand.
// PT canonical skill catalog - PT-Source/sinbaram/sinSkill{.h,_Info.h,.cpp}
// joined with Server/skill.ini per-rank tables.
//
// Row fields: class = our PlayerClass id; tier = PT job tier (CHANGE_JOB1..5);
// slot = position inside the tier (SKILL_1..4); requireLevel = base learn level
// (rank N requires requireLevel + (N-1)*2, sinSkill.cpp); stamina/mastery are
// {base, perRank}; element = PT Element[3]; weapons = sinXX UseWeaponCode
// whitelist (empty = any); hand = SIN_SKILL_USE_* (passive = USE_NOT);
// mana = per-rank mana table resolved from the row's UseMana key; ini = every
// skill.ini key sharing the row's mana-key prefix. PT_SKILL_ORDER keeps the
// sSkill[] table order - that order IS the learn-chain order (a skill stays
// locked until the previous list entry has >=1 point).`;

function jsStr(s) {
  return JSON.stringify(s);
}

function jsVal(v, indent = '') {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  if (typeof v === 'string') return jsStr(v);
  if (Array.isArray(v)) {
    if (!v.length) return '[]';
    if (v.every((x) => typeof x === 'number' || typeof x === 'string')) {
      return `[${v.map((x) => (typeof x === 'string' ? jsStr(x) : x)).join(', ')}]`;
    }
    const inner = v.map((x) => indent + '  ' + jsVal(x, indent + '  ')).join(',\n');
    return `[\n${inner},\n${indent}]`;
  }
  const keys = Object.keys(v);
  if (!keys.length) return '{}';
  const inner = keys
    .map((k) => `${indent}  ${/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : jsStr(k)}: ${jsVal(v[k], indent + '  ')}`)
    .join(',\n');
  return `{\n${inner},\n${indent}}`;
}

function readGbk(path) {
  return GBK.decode(readFileSync(path));
}

function main() {
  const skillHPath = ptSourcePath('sinbaram/sinSkill.h');
  const skillCppPath = ptSourcePath('sinbaram/sinSkill.cpp');
  const skillInfoPath = ptSourcePath('sinbaram/sinSkill_Info.h');
  const skillIniPath = ptServerPath('skill.ini');
  for (const p of [skillHPath, skillCppPath, skillInfoPath, skillIniPath]) {
    if (!existsSync(p)) {
      console.error(`missing PT source file: ${p}`);
      console.error('set PT_SOURCE_DIR / PT_SERVER_DIR to the MagicPT-Chinese checkout');
      process.exit(1);
    }
  }

  const { rows } = buildSkillCatalog({
    skillH: readGbk(skillHPath),
    skillCpp: readGbk(skillCppPath),
    skillInfoH: readGbk(skillInfoPath),
    skillIni: readGbk(skillIniPath),
  });

  const catalog = {};
  const order = {};
  for (const r of rows) {
    catalog[r.id] = r;
    (order[r.class] ||= []).push(r.id);
  }

  const lines = [HEADER, ''];
  lines.push(`export const PT_SKILL_CATALOG = ${jsVal(catalog)};`);
  lines.push('');
  lines.push(`export const PT_SKILL_ORDER = ${jsVal(order)};`);
  lines.push('');

  const genDir = join(repoRoot, 'generated', 'pt-maps');
  mkdirSync(genDir, { recursive: true });
  const out = join(genDir, 'pt_skill_catalog.generated.ts');
  writeFileSync(out, lines.join('\n'));

  const perClass = Object.fromEntries(
    Object.entries(order).map(([k, v]) => [k, v.length]),
  );
  console.log(`pt skill catalog: ${rows.length} skills across ${Object.keys(order).length} classes`);
  for (const [cls, n] of Object.entries(perClass)) console.log(`  ${cls}: ${n}`);
  console.log(`wrote ${out}`);
}

main();
